### ISSUE TITLE
Release latest version

### ISSUE THREAD

**Issue by hgrubst** [bhoriuchi/leaderfeed#1]
Hi,
Thanks for this project, it looks quite useful to tackle the not so easy issue of electing a leader without having to resort to other technologies.

Do you think you could publish the latest version 0.3 to npm please ? Currently only version 0.2 is published.

Thanks

**Comment by bhoriuchi** [comment]
I think I was mid development in redis when I took a break from this project. I can probably publish a beta version to npm

**Comment by hgrubst** [comment]
That would be good enough for us now, thanks.

**Comment by bhoriuchi** [comment]
Release `v0.3.0-alpha.0` has been published to npm. not thoroughly tested.

**Comment by hgrubst** [comment]
Thanks
